const { CreditCard } = require('../models');

const creditCardsData = [
  {
    name: "HDFC Regalia Credit Card",
    issuer: "HDFC Bank",
    joiningFee: 2500,
    annualFee: 2500,
    rewardType: "points",
    rewardRate: "4X points on all spends",
    eligibilityCriteria: "Minimum income: ₹12 lakhs per annum, Good credit score",
    perks: "Complimentary airport lounge access, Travel insurance, Golf privileges, Concierge services",
    affiliateLink: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia",
    imageUrl: "https://via.placeholder.com/300x200?text=HDFC+Regalia",
    minIncome: 1200000,
    creditScore: 750,
    category: "travel"
  },
  {
    name: "SBI SimplyCLICK Credit Card",
    issuer: "State Bank of India",
    joiningFee: 999,
    annualFee: 999,
    rewardType: "cashback",
    rewardRate: "10% cashback on online spends, 5% on dining, 1% on all other spends",
    eligibilityCriteria: "Minimum income: ₹6 lakhs per annum",
    perks: "Welcome voucher worth ₹2000, Movie ticket discounts, Fuel surcharge waiver",
    affiliateLink: "https://www.sbicard.com/en/personal/credit-cards/rewards/simplyclick.page",
    imageUrl: "https://via.placeholder.com/300x200?text=SBI+SimplyCLICK",
    minIncome: 600000,
    creditScore: 700,
    category: "shopping"
  },
  {
    name: "ICICI Amazon Pay Credit Card",
    issuer: "ICICI Bank",
    joiningFee: 0,
    annualFee: 0,
    rewardType: "cashback",
    rewardRate: "5% cashback on Amazon, 2% on Amazon Pay, 1% on all other spends",
    eligibilityCriteria: "Amazon Prime membership, Good credit score",
    perks: "No joining fee, No annual fee, Fuel surcharge waiver, Contactless payments",
    affiliateLink: "https://www.icicibank.com/Personal-Banking/cards/credit-card/amazon-pay-credit-card/index.page",
    imageUrl: "https://via.placeholder.com/300x200?text=ICICI+Amazon+Pay",
    minIncome: 400000,
    creditScore: 650,
    category: "shopping"
  },
  {
    name: "Axis Flipkart Credit Card",
    issuer: "Axis Bank",
    joiningFee: 500,
    annualFee: 500,
    rewardType: "cashback",
    rewardRate: "5% unlimited cashback on Flipkart, 4% on preferred merchants, 1% on all spends",
    eligibilityCriteria: "Minimum income: ₹4 lakhs per annum",
    perks: "Welcome voucher worth ₹1000, Fuel surcharge waiver, Contactless payments",
    affiliateLink: "https://www.axisbank.com/retail/cards/credit-card/flipkart-axis-bank-credit-card",
    imageUrl: "https://via.placeholder.com/300x200?text=Axis+Flipkart",
    minIncome: 400000,
    creditScore: 650,
    category: "shopping"
  },
  {
    name: "Citi PremierMiles Credit Card",
    issuer: "Citibank",
    joiningFee: 3000,
    annualFee: 3000,
    rewardType: "miles",
    rewardRate: "2.5X miles on all spends, 4X on dining and entertainment",
    eligibilityCriteria: "Minimum income: ₹15 lakhs per annum, Excellent credit score",
    perks: "Complimentary airport lounge access, Travel insurance, Concierge services, Golf privileges",
    affiliateLink: "https://www.citibank.co.in/credit-card/premiermiles",
    imageUrl: "https://via.placeholder.com/300x200?text=Citi+PremierMiles",
    minIncome: 1500000,
    creditScore: 750,
    category: "travel"
  },
  {
    name: "Kotak Urbane Credit Card",
    issuer: "Kotak Mahindra Bank",
    joiningFee: 0,
    annualFee: 0,
    rewardType: "cashback",
    rewardRate: "5% cashback on dining, 2% on fuel, 1% on all other spends",
    eligibilityCriteria: "Minimum income: ₹6 lakhs per annum",
    perks: "No joining fee, No annual fee, Fuel surcharge waiver, Movie ticket discounts",
    affiliateLink: "https://www.kotak.com/en/personal-banking/cards/credit-cards/urbane-credit-card.html",
    imageUrl: "https://via.placeholder.com/300x200?text=Kotak+Urbane",
    minIncome: 600000,
    creditScore: 700,
    category: "dining"
  },
  {
    name: "HDFC Diners Club Black Credit Card",
    issuer: "HDFC Bank",
    joiningFee: 10000,
    annualFee: 10000,
    rewardType: "points",
    rewardRate: "8X points on dining, 4X on travel, 2X on all other spends",
    eligibilityCriteria: "Minimum income: ₹25 lakhs per annum, Excellent credit score",
    perks: "Unlimited airport lounge access, Travel insurance, Concierge services, Golf privileges",
    affiliateLink: "https://www.hdfcbank.com/personal/pay/cards/credit-cards/diners-club-black",
    imageUrl: "https://via.placeholder.com/300x200?text=HDFC+Diners+Black",
    minIncome: 2500000,
    creditScore: 800,
    category: "dining"
  },
  {
    name: "BPCL SBI Credit Card",
    issuer: "State Bank of India",
    joiningFee: 500,
    annualFee: 500,
    rewardType: "cashback",
    rewardRate: "4.25% cashback on fuel at BPCL, 1% on all other spends",
    eligibilityCriteria: "Minimum income: ₹3 lakhs per annum",
    perks: "Fuel surcharge waiver, Welcome voucher, Movie ticket discounts",
    affiliateLink: "https://www.sbicard.com/en/personal/credit-cards/fuel/bpcl-sbi-credit-card.page",
    imageUrl: "https://via.placeholder.com/300x200?text=BPCL+SBI",
    minIncome: 300000,
    creditScore: 650,
    category: "fuel"
  },
  {
    name: "Axis Vistara Credit Card",
    issuer: "Axis Bank",
    joiningFee: 3000,
    annualFee: 3000,
    rewardType: "miles",
    rewardRate: "4X miles on Vistara flights, 2X on dining, 1X on all other spends",
    eligibilityCriteria: "Minimum income: ₹8 lakhs per annum",
    perks: "Complimentary airport lounge access, Travel insurance, Vistara privileges",
    affiliateLink: "https://www.axisbank.com/retail/cards/credit-card/vistara-axis-bank-credit-card",
    imageUrl: "https://via.placeholder.com/300x200?text=Axis+Vistara",
    minIncome: 800000,
    creditScore: 700,
    category: "travel"
  },
  {
    name: "RBL Shoprite Credit Card",
    issuer: "RBL Bank",
    joiningFee: 0,
    annualFee: 0,
    rewardType: "cashback",
    rewardRate: "5% cashback on grocery, 2% on fuel, 1% on all other spends",
    eligibilityCriteria: "Minimum income: ₹3 lakhs per annum",
    perks: "No joining fee, No annual fee, Fuel surcharge waiver, Welcome voucher",
    affiliateLink: "https://www.rblbank.com/credit-cards/shoprite-credit-card",
    imageUrl: "https://via.placeholder.com/300x200?text=RBL+Shoprite",
    minIncome: 300000,
    creditScore: 650,
    category: "shopping"
  },
  {
    name: "IndusInd Nexxt Credit Card",
    issuer: "IndusInd Bank",
    joiningFee: 0,
    annualFee: 0,
    rewardType: "cashback",
    rewardRate: "5% cashback on dining, 2% on fuel, 1% on all other spends",
    eligibilityCriteria: "Minimum income: ₹4 lakhs per annum",
    perks: "No joining fee, No annual fee, Fuel surcharge waiver, Movie ticket discounts",
    affiliateLink: "https://www.indusind.com/in/en/personal/cards/credit-cards/nexxt-credit-card.html",
    imageUrl: "https://via.placeholder.com/300x200?text=IndusInd+Nexxt",
    minIncome: 400000,
    creditScore: 650,
    category: "dining"
  },
  {
    name: "YES First Exclusive Credit Card",
    issuer: "YES Bank",
    joiningFee: 9999,
    annualFee: 9999,
    rewardType: "points",
    rewardRate: "6X points on dining, 4X on travel, 2X on all other spends",
    eligibilityCriteria: "Minimum income: ₹20 lakhs per annum, Excellent credit score",
    perks: "Unlimited airport lounge access, Travel insurance, Concierge services, Golf privileges",
    affiliateLink: "https://www.yesbank.in/personal-banking/yes-first/credit-cards/first-exclusive",
    imageUrl: "https://via.placeholder.com/300x200?text=YES+First+Exclusive",
    minIncome: 2000000,
    creditScore: 800,
    category: "dining"
  },
  {
    name: "Standard Chartered Rewards Credit Card",
    issuer: "Standard Chartered Bank",
    joiningFee: 0,
    annualFee: 0,
    rewardType: "points",
    rewardRate: "10X points on dining, 5X on groceries, 1X on all other spends",
    eligibilityCriteria: "Minimum income: ₹6 lakhs per annum",
    perks: "No joining fee, No annual fee, Welcome voucher, Movie ticket discounts",
    affiliateLink: "https://www.sc.com/in/credit-cards/rewards-credit-card/",
    imageUrl: "https://via.placeholder.com/300x200?text=SC+Rewards",
    minIncome: 600000,
    creditScore: 700,
    category: "dining"
  },
  {
    name: "HSBC Visa Signature Credit Card",
    issuer: "HSBC Bank",
    joiningFee: 2500,
    annualFee: 2500,
    rewardType: "points",
    rewardRate: "3X points on dining, 2X on travel, 1X on all other spends",
    eligibilityCriteria: "Minimum income: ₹12 lakhs per annum",
    perks: "Complimentary airport lounge access, Travel insurance, Concierge services",
    affiliateLink: "https://www.hsbc.co.in/credit-cards/products/visa-signature/",
    imageUrl: "https://via.placeholder.com/300x200?text=HSBC+Visa+Signature",
    minIncome: 1200000,
    creditScore: 750,
    category: "travel"
  },
  {
    name: "Federal Celesta Credit Card",
    issuer: "Federal Bank",
    joiningFee: 0,
    annualFee: 0,
    rewardType: "cashback",
    rewardRate: "5% cashback on dining, 2% on fuel, 1% on all other spends",
    eligibilityCriteria: "Minimum income: ₹4 lakhs per annum",
    perks: "No joining fee, No annual fee, Fuel surcharge waiver, Welcome voucher",
    affiliateLink: "https://www.federalbank.co.in/credit-cards/celesta-credit-card",
    imageUrl: "https://via.placeholder.com/300x200?text=Federal+Celesta",
    minIncome: 400000,
    creditScore: 650,
    category: "dining"
  },
  {
    name: "AU LIT Credit Card",
    issuer: "AU Small Finance Bank",
    joiningFee: 0,
    annualFee: 0,
    rewardType: "cashback",
    rewardRate: "5% cashback on dining, 2% on fuel, 1% on all other spends",
    eligibilityCriteria: "Minimum income: ₹3 lakhs per annum",
    perks: "No joining fee, No annual fee, Fuel surcharge waiver, Welcome voucher",
    affiliateLink: "https://www.aubank.in/credit-cards/lit-credit-card",
    imageUrl: "https://via.placeholder.com/300x200?text=AU+LIT",
    minIncome: 300000,
    creditScore: 650,
    category: "dining"
  },
  {
    name: "IDFC First Wow Credit Card",
    issuer: "IDFC First Bank",
    joiningFee: 0,
    annualFee: 0,
    rewardType: "cashback",
    rewardRate: "10% cashback on dining, 5% on groceries, 1% on all other spends",
    eligibilityCriteria: "Minimum income: ₹5 lakhs per annum",
    perks: "No joining fee, No annual fee, Welcome voucher, Movie ticket discounts",
    affiliateLink: "https://www.idfcfirstbank.com/credit-cards/wow-credit-card",
    imageUrl: "https://via.placeholder.com/300x200?text=IDFC+Wow",
    minIncome: 500000,
    creditScore: 700,
    category: "dining"
  },
  {
    name: "PNB Rupay Credit Card",
    issuer: "Punjab National Bank",
    joiningFee: 500,
    annualFee: 500,
    rewardType: "cashback",
    rewardRate: "2% cashback on fuel, 1% on all other spends",
    eligibilityCriteria: "Minimum income: ₹3 lakhs per annum",
    perks: "Fuel surcharge waiver, Welcome voucher, Contactless payments",
    affiliateLink: "https://www.pnbcards.in/credit-cards/rupay-credit-card",
    imageUrl: "https://via.placeholder.com/300x200?text=PNB+Rupay",
    minIncome: 300000,
    creditScore: 650,
    category: "fuel"
  },
  {
    name: "Bank of Baroda Premier Credit Card",
    issuer: "Bank of Baroda",
    joiningFee: 2000,
    annualFee: 2000,
    rewardType: "points",
    rewardRate: "4X points on dining, 2X on travel, 1X on all other spends",
    eligibilityCriteria: "Minimum income: ₹8 lakhs per annum",
    perks: "Complimentary airport lounge access, Travel insurance, Concierge services",
    affiliateLink: "https://www.bobcard.in/credit-cards/premier-credit-card",
    imageUrl: "https://via.placeholder.com/300x200?text=BOB+Premier",
    minIncome: 800000,
    creditScore: 700,
    category: "dining"
  },
  {
    name: "Canara Bank Rupay Credit Card",
    issuer: "Canara Bank",
    joiningFee: 500,
    annualFee: 500,
    rewardType: "cashback",
    rewardRate: "2% cashback on fuel, 1% on all other spends",
    eligibilityCriteria: "Minimum income: ₹3 lakhs per annum",
    perks: "Fuel surcharge waiver, Welcome voucher, Contactless payments",
    affiliateLink: "https://canarabank.com/credit-cards/rupay-credit-card",
    imageUrl: "https://via.placeholder.com/300x200?text=Canara+Rupay",
    minIncome: 300000,
    creditScore: 650,
    category: "fuel"
  },
  {
    name: "Union Bank Rupay Credit Card",
    issuer: "Union Bank of India",
    joiningFee: 500,
    annualFee: 500,
    rewardType: "cashback",
    rewardRate: "2% cashback on fuel, 1% on all other spends",
    eligibilityCriteria: "Minimum income: ₹3 lakhs per annum",
    perks: "Fuel surcharge waiver, Welcome voucher, Contactless payments",
    affiliateLink: "https://www.unionbankofindia.co.in/english/credit-cards.aspx",
    imageUrl: "https://via.placeholder.com/300x200?text=Union+Rupay",
    minIncome: 300000,
    creditScore: 650,
    category: "fuel"
  }
];

async function seedCreditCards() {
  try {
    // Clear existing data
    await CreditCard.destroy({ where: {} });
    
    // Insert new data
    await CreditCard.bulkCreate(creditCardsData);
    
    console.log('Credit cards seeded successfully!');
  } catch (error) {
    console.error('Error seeding credit cards:', error);
  }
}

module.exports = { seedCreditCards }; 